[package]
name = "traefik-gui"
version = "0.1.2"
edition = "2021"

[dependencies]
rocket = "0.5.1"
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.18"
itertools = "0.14.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "uuid", "macros", "migrate"] }
uuid = { version = "1.19.0", features = ["v4", "serde"] }
